/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ChuyenVien;


/**
 *
 * @author bvndc
 */
import DVHC.*;
import ICD.*;
import KhoaPhong.*;
import TongHop.*;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.JSpinner;

public class JDialogChuyenDi extends javax.swing.JDialog {

    /**
     * Creates new form JDialogChuyenDi
     */
    private ArrayList<KhoaPhong> lstKP;
    private ArrayList<DoiTuong> lstDT;
    private ArrayList<PhuongTien> lstPT;
    private ArrayList<LyDo> lstLD;
    
    private ChuyenDi chuyenDi;
    private BenhNhan benhNhan;
    
    private String maXP;
    private String chuyenVienID;
    private Date ngayChuyen;
    private String maBS;
    private String benhVienID;
    private int noiTru;
    private Date tuNgay;
    private Date denNgay;
    
    ActionDVHC actDVHC = new ActionDVHC();
    ActionKhoaPhong actKhoaPhong = new ActionKhoaPhong();
    ActionDoiTuong actDoiTuong = new ActionDoiTuong();
    ActionBenhVien actBenhVien = new ActionBenhVien();
    ActionLyDo actLyDo = new ActionLyDo();
    ActionPhuongTien actPT = new ActionPhuongTien();
    ActionICDBenh actICD = new ActionICDBenh();
    ActionBacSi actBS = new ActionBacSi();
    ActionChuyenDi actCD = new ActionChuyenDi();
    ActionBenhNhan actBN = new ActionBenhNhan();
    
    public JDialogChuyenDi(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogChuyenDi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHanhChinh = new javax.swing.JPanel();
        chkTraiTuyen = new javax.swing.JCheckBox();
        cboDoiTuong = new javax.swing.JComboBox();
        lblDoiTuong = new javax.swing.JLabel();
        lblSoBHYT = new javax.swing.JLabel();
        txtSoBHYT = new javax.swing.JTextField();
        lblHoTenBN = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        lblMaBN = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        txtNamSinh = new javax.swing.JFormattedTextField();
        lblNamSinh = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox();
        pnlChuyenVien = new javax.swing.JPanel();
        cboKhoaPhong = new javax.swing.JComboBox();
        lblKhoaChuyen = new javax.swing.JLabel();
        txtBenhVien = new javax.swing.JTextField();
        lblBenhVien = new javax.swing.JLabel();
        lblBenhICD = new javax.swing.JLabel();
        txtMaBenh = new javax.swing.JTextField();
        txtTenBenh = new javax.swing.JTextField();
        lblBacSi = new javax.swing.JLabel();
        txtBacSi = new javax.swing.JTextField();
        lblLyDo = new javax.swing.JLabel();
        cboLyDo = new javax.swing.JComboBox();
        lblPhuongTien = new javax.swing.JLabel();
        cboPhuongTien = new javax.swing.JComboBox();
        lblTuNgay = new javax.swing.JLabel();
        lblDenNgay = new javax.swing.JLabel();
        lblNgayChuyen = new javax.swing.JLabel();
        txtSoChuyen = new javax.swing.JTextField();
        lblSoChuyen = new javax.swing.JLabel();
        txtTuNgay = new javax.swing.JSpinner();
        txtDenNgay = new javax.swing.JSpinner();
        txtNgayChuyen = new javax.swing.JSpinner();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin chuyển viện");
        setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlHanhChinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin hành chính"));

        chkTraiTuyen.setText("Trái tuyến");
        chkTraiTuyen.setNextFocusableComponent(cboKhoaPhong);

        cboDoiTuong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDoiTuong.setNextFocusableComponent(txtSoBHYT);
        cboDoiTuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDoiTuongItemStateChanged(evt);
            }
        });

        lblDoiTuong.setText("Đối tượng:");

        lblSoBHYT.setText("Số BHYT:");

        txtSoBHYT.setNextFocusableComponent(chkTraiTuyen);
        txtSoBHYT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoBHYTKeyTyped(evt);
            }
        });

        lblHoTenBN.setText("Họ tên BN:");

        txtMaBN.setNextFocusableComponent(txtHoTen);
        txtMaBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaBNKeyPressed(evt);
            }
        });

        lblMaBN.setText("Mã BN:");

        txtDiaChi.setNextFocusableComponent(cboDoiTuong);
        txtDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusLost(evt);
            }
        });

        lblGioiTinh.setText("Phái:");

        txtNamSinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        txtNamSinh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNamSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNamSinh.setNextFocusableComponent(cboGioiTinh);
        txtNamSinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamSinhFocusGained(evt);
            }
        });
        txtNamSinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamSinhKeyTyped(evt);
            }
        });

        lblNamSinh.setText("Năm sinh:");

        txtHoTen.setNextFocusableComponent(txtNamSinh);
        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoTenKeyTyped(evt);
            }
        });

        lblDiaChi.setText("Địa chỉ:");

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nữ", "Nam" }));
        cboGioiTinh.setNextFocusableComponent(txtDiaChi);

        javax.swing.GroupLayout pnlHanhChinhLayout = new javax.swing.GroupLayout(pnlHanhChinh);
        pnlHanhChinh.setLayout(pnlHanhChinhLayout);
        pnlHanhChinhLayout.setHorizontalGroup(
            pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHanhChinhLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDoiTuong)
                    .addComponent(lblDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHanhChinhLayout.createSequentialGroup()
                        .addComponent(cboDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblSoBHYT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkTraiTuyen)
                        .addContainerGap())
                    .addComponent(txtDiaChi)))
            .addGroup(pnlHanhChinhLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMaBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoTenBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamSinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGioiTinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHanhChinhLayout.setVerticalGroup(
            pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHanhChinhLayout.createSequentialGroup()
                .addGroup(pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBN)
                    .addComponent(lblHoTenBN)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamSinh)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioiTinh)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHanhChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoiTuong)
                    .addComponent(lblSoBHYT)
                    .addComponent(txtSoBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTraiTuyen)))
        );

        pnlChuyenVien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin chuyển viện"));

        cboKhoaPhong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhoaPhong.setNextFocusableComponent(txtBenhVien);

        lblKhoaChuyen.setText("Khoa:");

        txtBenhVien.setNextFocusableComponent(txtMaBenh);
        txtBenhVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBenhVienFocusLost(evt);
            }
        });

        lblBenhVien.setText("Bệnh viện:");

        lblBenhICD.setText("Bệnh ICD:");

        txtMaBenh.setNextFocusableComponent(txtBacSi);
        txtMaBenh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaBenhFocusLost(evt);
            }
        });
        txtMaBenh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaBenhKeyTyped(evt);
            }
        });

        txtTenBenh.setEditable(false);

        lblBacSi.setText("Bác sĩ:");

        txtBacSi.setNextFocusableComponent(cboLyDo);
        txtBacSi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBacSiFocusLost(evt);
            }
        });

        lblLyDo.setText("Lý do:");

        cboLyDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLyDo.setNextFocusableComponent(cboPhuongTien);

        lblPhuongTien.setText("Phương tiện:");

        cboPhuongTien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPhuongTien.setNextFocusableComponent(txtTuNgay);

        lblTuNgay.setText("Điều trị từ:");

        lblDenNgay.setText("Đến ngày:");

        lblNgayChuyen.setText("Ngày chuyển:");

        txtSoChuyen.setEditable(false);
        txtSoChuyen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtSoChuyen.setForeground(java.awt.Color.red);
        txtSoChuyen.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblSoChuyen.setText("Số chuyển:");

        txtTuNgay.setModel(new javax.swing.SpinnerDateModel());
        txtTuNgay.setEditor(new javax.swing.JSpinner.DateEditor(txtTuNgay, "dd/MM/yyyy"));

        txtDenNgay.setModel(new javax.swing.SpinnerDateModel());
        txtDenNgay.setEditor(new javax.swing.JSpinner.DateEditor(txtDenNgay, "dd/MM/yyyy"));

        txtNgayChuyen.setModel(new javax.swing.SpinnerDateModel());
        txtNgayChuyen.setEditor(new javax.swing.JSpinner.DateEditor(txtNgayChuyen, "dd/MM/yyyy"));
        txtNgayChuyen.setNextFocusableComponent(btnSave);

        javax.swing.GroupLayout pnlChuyenVienLayout = new javax.swing.GroupLayout(pnlChuyenVien);
        pnlChuyenVien.setLayout(pnlChuyenVienLayout);
        pnlChuyenVienLayout.setHorizontalGroup(
            pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlChuyenVienLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBenhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                        .addComponent(txtMaBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                        .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhuongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNgayChuyen, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                                .addComponent(cboPhuongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTuNgay))
                            .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                                .addComponent(txtNgayChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(lblSoChuyen)))
                        .addGap(3, 3, 3)
                        .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                                .addComponent(txtSoChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTuNgay))
                        .addGap(18, 18, 18)
                        .addComponent(lblDenNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBacSi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBenhICD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKhoaChuyen, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBacSi)
                            .addComponent(cboKhoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBenhVien, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLyDo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        pnlChuyenVienLayout.setVerticalGroup(
            pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenVienLayout.createSequentialGroup()
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhoaChuyen)
                    .addComponent(cboKhoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBenhVien)
                    .addComponent(txtBenhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaBenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBenhICD)
                    .addComponent(txtTenBenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBacSi)
                    .addComponent(txtBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLyDo)
                    .addComponent(cboLyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhuongTien)
                    .addComponent(lblTuNgay)
                    .addComponent(lblDenNgay)
                    .addComponent(cboPhuongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChuyenVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayChuyen)
                    .addComponent(txtSoChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoChuyen)
                    .addComponent(txtNgayChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewDocumentHS.png"))); // NOI18N
        btnNew.setText("Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/saveHS.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setNextFocusableComponent(btnNew);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GoToParentFolderHS.png"))); // NOI18N
        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlHanhChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlChuyenVien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHanhChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlChuyenVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave)
                    .addComponent(btnNew))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusLost
        try {
           if (txtDiaChi.getText().trim().length() == 0){
               maXP = "";
               return;
           }
            try (ResultSet rs = actDVHC.getAllDVHC(txtDiaChi.getText())) {
                rs.last();
                if (rs.getRow() > 0){
                    if (rs.getRow() > 1){
                        JDialogSearchDVHC frm = new JDialogSearchDVHC((Frame) this.getParent(), true);
                        rs.first();
                        frm.showData(rs);
                        frm.setVisible(true);
                        rs.absolute(frm.getIndexSelected() + 1);
                        rs.next();
                    }
                    else {
                        rs.first();
                    }
                    txtDiaChi.setText(rs.getString("TenDVHC"));
                    maXP = rs.getString("MaXP");
                }
                else{
                    maXP = "";
                    txtDiaChi.setText("");
                }}
        } catch (Exception e) {
            e.printStackTrace();
        }      
    }//GEN-LAST:event_txtDiaChiFocusLost
    private void khoiTao(){
        txtNgayChuyen.setValue(Date.valueOf(LocalDate.now()));
        txtTuNgay.setValue(Date.valueOf(LocalDate.now()));
        txtDenNgay.setValue(Date.valueOf(LocalDate.now()));
        txtNamSinh.setText(String.valueOf(LocalDate.now().getYear()));
    }
    private void loadBenhNhan(String maBN) throws Exception{
        try {
            benhNhan = actBN.getBenhNhan(maBN);
            txtMaBN.setText(benhNhan.getMaBN());
            txtHoTen.setText(benhNhan.getHoTen());
            txtNamSinh.setText(String.valueOf(benhNhan.getNamSinh()));
            cboGioiTinh.setSelectedIndex(benhNhan.getGioiTinh());
            maXP = benhNhan.getMaXP();
            txtDiaChi.setText(actDVHC.getTenDVHC(maXP));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void loadChuyenDi() throws Exception{
        if (getChuyenDiID() == null || getChuyenDiID().length() == 0) return;
        chuyenDi = actCD.getChuyenDi(getChuyenDiID());
        loadBenhNhan(chuyenDi.getMaBN());
        cboDoiTuong.setSelectedIndex(actDoiTuong.getIndexDoiTuong(lstDT, chuyenDi.getDoiTuongID()));
        txtSoBHYT.setText(chuyenDi.getSoBHYT());
        chkTraiTuyen.setSelected(chuyenDi.getTraiTuyen() == 1? true : false);
        cboKhoaPhong.setSelectedIndex(actKhoaPhong.getIndexKhoaPhong(lstKP, chuyenDi.getMaKP()));
        benhVienID = chuyenDi.getBenhVienID();
        txtBenhVien.setText(actBenhVien.getTenBenhVien(chuyenDi.getBenhVienID()));
        txtMaBenh.setText(chuyenDi.getIcdBenhID());
        txtTenBenh.setText(actICD.getTenBenh(chuyenDi.getIcdBenhID()));
        maBS = chuyenDi.getMaBS();
        txtBacSi.setText(actBS.gethoTen(chuyenDi.getMaBS()));
        cboLyDo.setSelectedIndex(actLyDo.getIndexLyDo(lstLD, chuyenDi.getLyDoID()));
        cboPhuongTien.setSelectedIndex(actPT.getIndexPhuongTien(lstPT, chuyenDi.getPhuongTienID()));
        txtNgayChuyen.setValue(chuyenDi.getNgayChuyen());
        txtTuNgay.setValue(chuyenDi.getTuNgay());
        txtDenNgay.setValue(chuyenDi.getDenNgay());
        txtSoChuyen.setText(chuyenDi.getChuyenVienID());
    }
    private Boolean kiemTra(){
        Calendar c = Calendar.getInstance();
        JSpinner.DateEditor de = new JSpinner.DateEditor(txtTuNgay, "dd/MM/yyyy");
        tuNgay = Date.valueOf(LocalDate.parse(de.getFormat().format(txtTuNgay.getValue()), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        denNgay = Date.valueOf(LocalDate.parse(de.getFormat().format(txtDenNgay.getValue()), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        ngayChuyen = Date.valueOf(LocalDate.parse(de.getFormat().format(txtNgayChuyen.getValue()), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        if (txtHoTen.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập họ tên bệnh nhân!");
            txtHoTen.requestFocus();
            return false;
        }
        if (txtNamSinh.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập năm sinh!");
            txtNamSinh.requestFocus();
            return false;
        }
        if (LocalDate.now().getYear() < Integer.parseInt(txtNamSinh.getText())){
            JOptionPane.showMessageDialog(null, "Năm sinh sai!");
            txtNamSinh.requestFocus();
            return false;
        }
         if (txtDiaChi.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập địa chỉ bệnh nhân!");
            txtDiaChi.requestFocus();
            return false;
        }
        if (cboDoiTuong.getSelectedIndex() == 0 && txtSoBHYT.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập số BHYT!");
            txtSoBHYT.requestFocus();
            return false;
        }
         
        if (txtBenhVien.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập bệnh viện!");
            txtBenhVien.requestFocus();
            return false;
        }
         if (txtTenBenh.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập mã bệnh ICD!");
            txtMaBenh.requestFocus();
            return false;
        }
        if (txtBacSi.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Chưa nhập Bác sĩ!");
            txtBacSi.requestFocus();
            return false;
        }
      
        if (c.getTime().compareTo(tuNgay) < 0){
            JOptionPane.showMessageDialog(null, "Ngày không được lớn hơn ngày hiện hành!");
            txtTuNgay.requestFocus();
            return false;
        }
        if (c.getTime().compareTo(denNgay) < 0){
            JOptionPane.showMessageDialog(null, "Ngày không được lớn hơn ngày hiện hành!");
            txtDenNgay.requestFocus();
            return false;
        }
        if (c.getTime().compareTo(ngayChuyen) < 0){
            JOptionPane.showMessageDialog(null, "Ngày không được lớn hơn ngày hiện hành!");
            txtNgayChuyen.requestFocus();
            return false;
        }
        if (tuNgay.compareTo(denNgay) > 0){
            JOptionPane.showMessageDialog(null, "Ngày điều trị từ ngày không thể lớn hơn đến ngày!");
            txtTuNgay.requestFocus();
            return false;
            
        }
        if (ngayChuyen.compareTo(denNgay) < 0){
            JOptionPane.showMessageDialog(null, "Ngày chuyển không thể nhỏ hơn ngày điều trị!");
            txtNgayChuyen.requestFocus();
            return false;
        }
        return true;
    }
    private void txtNamSinhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamSinhKeyTyped
           if (!(Character.isDigit(evt.getKeyChar()) || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_DELETE))){
                evt.consume();  
           }  
    }//GEN-LAST:event_txtNamSinhKeyTyped

    private void txtHoTenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_txtHoTenKeyTyped

    private void txtSoBHYTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoBHYTKeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_txtSoBHYTKeyTyped

    private void cboDoiTuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDoiTuongItemStateChanged
        try {          
            txtSoBHYT.setEnabled(cboDoiTuong.getSelectedIndex() == 0);
            chkTraiTuyen.setEnabled(cboDoiTuong.getSelectedIndex() == 0);
            lblSoBHYT.setEnabled(cboDoiTuong.getSelectedIndex() == 0);
            chkTraiTuyen.setSelected(false);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_cboDoiTuongItemStateChanged

    private void txtBenhVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBenhVienFocusLost
        try {
            if (txtBenhVien.getText().trim().length() == 0){
                benhVienID = "";
                return;
            }
            try (ResultSet rs = actBenhVien.getListBenhVien(txtBenhVien.getText())) {
                rs.last();
                if (rs.getRow() > 0){
                    if (rs.getRow() > 1){
                        JDialogSearchBenhVien frm = new JDialogSearchBenhVien((Frame) this.getParent(), true);
                        rs.first();
                        frm.showData(rs);
                        frm.setVisible(true);
                        rs.absolute(frm.getIndexSelected() + 1);
                        rs.next();
                    }
                    else {
                        rs.first();
                    }
                    txtBenhVien.setText(rs.getString("TenBenhVien"));
                    benhVienID = rs.getString("BenhVienID");
                }
                else {
                    benhVienID = "";
                    txtBenhVien.setText("");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtBenhVienFocusLost

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    private void saveBenhNhan() throws Exception{
        benhNhan = new BenhNhan(txtMaBN.getText(), txtHoTen.getText(), Short.valueOf(txtNamSinh.getText()), Short.valueOf(String.valueOf(cboGioiTinh.getSelectedIndex())), maXP);
        txtMaBN.setText(actBN.saveData(benhNhan));    
    }
    private void saveChuyenDi(Short daChuyen) throws Exception{       
        chuyenDi = new ChuyenDi(getChuyenDiID(), 
                txtMaBN.getText(), 
                ngayChuyen, 
                lstKP.get(cboKhoaPhong.getSelectedIndex()).getMaKP(), 
                maBS, 
                lstDT.get(cboDoiTuong.getSelectedIndex()).getDoiTuongID(), 
                txtSoBHYT.getText(), 
                Short.valueOf(chkTraiTuyen.isSelected()? "1": "0"), 
                txtMaBenh.getText(),
                benhVienID, 
                lstPT.get(cboPhuongTien.getSelectedIndex()).getPhuongTienID(), 
                lstLD.get(cboLyDo.getSelectedIndex()).getLyDoID(), 
                daChuyen, 
                Short.valueOf(String.valueOf(getNoiTru())), 
                tuNgay, 
                denNgay);
        setChuyenDiID(actCD.saveData(chuyenDi));
        txtSoChuyen.setText(getChuyenDiID());
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!kiemTra()) return;
        try {
            saveBenhNhan();
            if (getNoiTru() == 0){
                saveChuyenDi(Short.valueOf("1"));
            } else {
                if (JOptionPane.showConfirmDialog(null, "Chuyển viện ngay bây giờ phải không?", "Chuyển viện", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                    saveChuyenDi(Short.valueOf("1"));
                } else {
                    saveChuyenDi(Short.valueOf("0"));
                }
            }
            btnNew.requestFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }  
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        khoiTao();
        txtMaBN.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (getNoiTru() == 1) 
            this.setTitle("Thông tin chuyển viện nội trú");
        else
            this.setTitle("Thông tin chuyển viện ngoại trú");
        try {
            loadDoiTuong();
            loadKhoaPhong();
            loadLyDo();
            loadPhuongTien();
            khoiTao();        
            loadChuyenDi();
        } catch (Exception e) {
            e.printStackTrace();
        }      
    }//GEN-LAST:event_formWindowOpened

    private void txtMaBenhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaBenhFocusLost
        if (txtMaBenh.getText().trim().length() == 0) return;
        try {
            try (ResultSet rs = actICD.getICDBenh(txtMaBenh.getText())) {
                rs.last();
                
                if (rs.getRow() > 0){
                    if (rs.getRow() > 1){
                        ICDSearch frm = new ICDSearch(null, true);
                        frm.setIcdBenhID(txtMaBenh.getText());
                        frm.setVisible(true);
                        txtMaBenh.setText(frm.getIcdBenhID());
                        txtTenBenh.setText(frm.getTenBenh());
                    }
                    else {
                        rs.first();
                        txtTenBenh.setText(rs.getString("TenBenh"));
                        txtMaBenh.setText(rs.getString("ICDBenhID"));
                    }
                }
                else{
                    txtTenBenh.setText("");
                    txtMaBenh.setText("");
                }}
        } catch (Exception e) {
            e.printStackTrace();
        }      
    }//GEN-LAST:event_txtMaBenhFocusLost

    private void txtMaBenhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaBenhKeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }

    }//GEN-LAST:event_txtMaBenhKeyTyped

    private void txtBacSiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBacSiFocusLost
        try {
            if (txtBacSi.getText().trim().length() == 0){
                maBS = "";
                return;
            }
            try (ResultSet rs = actBS.getListBacSi(txtBacSi.getText())) {
                rs.last();
                if (rs.getRow() > 0){
                    if (rs.getRow() > 1){
                        JDialogSearchBacSi frm = new JDialogSearchBacSi((Frame) this.getParent(), true);
                        rs.first();
                        frm.showData(rs);
                        frm.setVisible(true);
                        txtBacSi.setText(frm.getHoTen());
                        maBS = frm.getMaBS();
                    }
                    else {
                        rs.first();
                        txtBacSi.setText(rs.getString("HoTen"));
                        maBS = rs.getString("MaBS");
                    }
                }
                else {
                    maBS = "";
                    txtBacSi.setText("");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_txtBacSiFocusLost

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtHoTen.grabFocus();
    }//GEN-LAST:event_formKeyPressed

    private void txtMaBNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaBNKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            txtMaBN.transferFocus();
    }//GEN-LAST:event_txtMaBNKeyPressed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnSaveActionPerformed(null);
        }
    }//GEN-LAST:event_btnSaveKeyPressed

    private void txtNamSinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamSinhFocusGained
        txtNamSinh.selectAll();
    }//GEN-LAST:event_txtNamSinhFocusGained
    private void loadDoiTuong(){
        try {
            lstDT = actDoiTuong.getAllDoiTuong();
            cboDoiTuong.removeAllItems();
            for(DoiTuong dt:lstDT){
                cboDoiTuong.addItem(dt.getTenDoiTuong());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    
    private void loadKhoaPhong(){
        try {
            lstKP = actKhoaPhong.getAllKhoaPhong(noiTru == 0? "01" : "02");
            cboKhoaPhong.removeAllItems();
            for(KhoaPhong kp:lstKP){
                cboKhoaPhong.addItem(kp.getTenKP());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void loadLyDo(){
        try {
            lstLD = actLyDo.getAllLyDo();
            cboLyDo.removeAllItems();
            for(LyDo kp:lstLD){
                cboLyDo.addItem(kp.getTenLyDo());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void loadPhuongTien(){
        try {
            lstPT = actPT.getAllPhuongTien();
            cboPhuongTien.removeAllItems();
            for(PhuongTien pt:lstPT){
                cboPhuongTien.addItem(pt.getTenPhuongTien());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogChuyenDi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogChuyenDi dialog = new JDialogChuyenDi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboDoiTuong;
    private javax.swing.JComboBox cboGioiTinh;
    private javax.swing.JComboBox cboKhoaPhong;
    private javax.swing.JComboBox cboLyDo;
    private javax.swing.JComboBox cboPhuongTien;
    private javax.swing.JCheckBox chkTraiTuyen;
    private javax.swing.JLabel lblBacSi;
    private javax.swing.JLabel lblBenhICD;
    private javax.swing.JLabel lblBenhVien;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDoiTuong;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTenBN;
    private javax.swing.JLabel lblKhoaChuyen;
    private javax.swing.JLabel lblLyDo;
    private javax.swing.JLabel lblMaBN;
    private javax.swing.JLabel lblNamSinh;
    private javax.swing.JLabel lblNgayChuyen;
    private javax.swing.JLabel lblPhuongTien;
    private javax.swing.JLabel lblSoBHYT;
    private javax.swing.JLabel lblSoChuyen;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JPanel pnlChuyenVien;
    private javax.swing.JPanel pnlHanhChinh;
    private javax.swing.JTextField txtBacSi;
    private javax.swing.JTextField txtBenhVien;
    private javax.swing.JSpinner txtDenNgay;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtMaBenh;
    private javax.swing.JFormattedTextField txtNamSinh;
    private javax.swing.JSpinner txtNgayChuyen;
    private javax.swing.JTextField txtSoBHYT;
    private javax.swing.JTextField txtSoChuyen;
    private javax.swing.JTextField txtTenBenh;
    private javax.swing.JSpinner txtTuNgay;
    // End of variables declaration//GEN-END:variables

    public int getNoiTru() {
        return noiTru;
    }

    public void setNoiTru(int noiTru) {
        this.noiTru = noiTru;
    }

    public String getChuyenDiID() {
        return chuyenVienID;
    }

    public void setChuyenDiID(String chuyenDiID) {
        this.chuyenVienID = chuyenDiID;
    }
}
