/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package KHKT;

import DataDB2.*;
import KhoaPhong.*;
import NhanSu.*;
import java.awt.Frame;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author bvndc
 */
public class JInternalFrameListNCKH extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameListNCKH
     */
    ActionLoaiNC actLoaiNC = new ActionLoaiNC();
    ActionHe actHe = new ActionHe();
    ActionCap actCap = new ActionCap();
    ActionKhoaPhong actKP = new ActionKhoaPhong();
    ActionTenNCKH actTenNCKH = new ActionTenNCKH();
    ActionNhanVien actNV = new ActionNhanVien();
    ActionTacGia actTG = new ActionTacGia();
    
    ArrayList<LoaiNC> lstLoaiNC;
    ArrayList<He> lstHe;
    ArrayList<Cap> lstCap;
    ArrayList<KhoaPhong> lstKP;
    
    String maNV = "";
    
    public JInternalFrameListNCKH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuNew = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCongNhanNCKH = new javax.swing.JMenuItem();
        mnuHuyCongNhanNCKH = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuDuyetNop = new javax.swing.JMenuItem();
        mnuHuyDuyetNop = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        chkLoaiNC = new javax.swing.JCheckBox();
        chkCap = new javax.swing.JCheckBox();
        chkHe = new javax.swing.JCheckBox();
        chkKhoaPhong = new javax.swing.JCheckBox();
        cboLoaiNC = new javax.swing.JComboBox();
        cboCap = new javax.swing.JComboBox();
        cboHe = new javax.swing.JComboBox();
        cboKhoaPhong = new javax.swing.JComboBox();
        txtTacGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chkCongNhan = new javax.swing.JCheckBox();
        chkNop = new javax.swing.JCheckBox();
        lblTongSo = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnInQD = new javax.swing.JButton();
        txtNam = new javax.swing.JSpinner();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCongNhanNCKH = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        mnuNew.setText("Thêm...");
        mnuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuNew);

        mnuEdit.setText("Sửa...");
        mnuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuEdit);

        mnuDelete.setText("Xoá...");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuDelete);
        jPopupMenu1.add(jSeparator1);

        mnuCongNhanNCKH.setText("Quyết định công nhận NCKH...");
        mnuCongNhanNCKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCongNhanNCKHActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuCongNhanNCKH);

        mnuHuyCongNhanNCKH.setText("Huỷ công nhận đề tài, sáng kiến");
        mnuHuyCongNhanNCKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHuyCongNhanNCKHActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuHuyCongNhanNCKH);
        jPopupMenu1.add(jSeparator2);

        mnuDuyetNop.setText("Duyệt nộp đề tài, sáng kiến");
        mnuDuyetNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDuyetNopActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuDuyetNop);

        mnuHuyDuyetNop.setText("Huỷ duyệt nộp đề tài, sáng kiến");
        mnuHuyDuyetNop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHuyDuyetNopActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuHuyDuyetNop);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Danh sách các đề tài, sáng kiến");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Năm NC:");

        chkLoaiNC.setText("Loại:");
        chkLoaiNC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkLoaiNCItemStateChanged(evt);
            }
        });

        chkCap.setText("Cấp:");
        chkCap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCapItemStateChanged(evt);
            }
        });

        chkHe.setText("Hệ:");
        chkHe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkHeItemStateChanged(evt);
            }
        });

        chkKhoaPhong.setText("Khoa:");
        chkKhoaPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkKhoaPhongItemStateChanged(evt);
            }
        });

        cboLoaiNC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiNC.setEnabled(false);

        cboCap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCap.setEnabled(false);

        cboHe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHe.setEnabled(false);

        cboKhoaPhong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhoaPhong.setEnabled(false);

        txtTacGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTacGiaFocusLost(evt);
            }
        });

        jLabel2.setText("Tác giả:");

        chkCongNhan.setText("Danh sách đề tài được công nhận");

        chkNop.setText("Danh sách đề tài đã nộp");

        lblTongSo.setForeground(java.awt.Color.red);
        lblTongSo.setText("Tổng số: 0");

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RefreshDocViewHS.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Excel.jpg"))); // NOI18N
        btnExcel.setText("Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnInQD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PrintPreviewHS.png"))); // NOI18N
        btnInQD.setText("In QĐ");

        txtNam.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)2014), Short.valueOf((short)2014), Short.valueOf((short)9999), Short.valueOf((short)1)));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NewDocumentHS.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EditTableHS.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DeleteHS.png"))); // NOI18N
        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCongNhanNCKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlayHS.png"))); // NOI18N
        btnCongNhanNCKH.setText("Công nhận NCKH");
        btnCongNhanNCKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongNhanNCKHActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GoToParentFolderHS.png"))); // NOI18N
        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCap)
                            .addComponent(chkHe)
                            .addComponent(chkLoaiNC)
                            .addComponent(chkKhoaPhong)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTongSo))
                            .addComponent(cboKhoaPhong, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHe, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboCap, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTacGia)
                            .addComponent(cboLoaiNC, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCongNhanNCKH, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCongNhan)
                            .addComponent(chkNop)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnExcel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnInQD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEdit, btnExcel});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnInQD});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNew, btnRefresh});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTongSo)
                    .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLoaiNC)
                    .addComponent(cboLoaiNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCap)
                    .addComponent(cboCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHe)
                    .addComponent(cboHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkKhoaPhong)
                    .addComponent(cboKhoaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCongNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkNop)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnExcel)
                    .addComponent(btnInQD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCongNhanNCKH)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(javax.swing.UIManager.getDefaults().getColor("ArrowButton.background"));
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            this.setMaximum(true);
            txtNam.setValue(LocalDate.now().getYear());
            loadData();
            btnRefreshActionPerformed(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void chkLoaiNCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkLoaiNCItemStateChanged
        cboLoaiNC.setEnabled(chkLoaiNC.isSelected());
    }//GEN-LAST:event_chkLoaiNCItemStateChanged

    private void chkCapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCapItemStateChanged
        cboCap.setEnabled(chkCap.isSelected());
    }//GEN-LAST:event_chkCapItemStateChanged

    private void chkHeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkHeItemStateChanged
        cboHe.setEnabled(chkHe.isSelected());
    }//GEN-LAST:event_chkHeItemStateChanged

    private void chkKhoaPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkKhoaPhongItemStateChanged
        cboKhoaPhong.setEnabled(chkKhoaPhong.isSelected());
    }//GEN-LAST:event_chkKhoaPhongItemStateChanged
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            String[] header = {"Nộp", "Mã số", "Tên NCKH", "Cấp", "Hệ", "Ngày ĐK", "Được CN", "Ngày CN", "Số QĐ", "Loại nghiên cứu", "Năm", "Tác giả"};
            FillData fillData = new FillData();
            ResultSet rs = actTenNCKH.getListNCKH(Integer.parseInt(txtNam.getValue().toString()),
                    chkLoaiNC.isSelected()? lstLoaiNC.get(cboLoaiNC.getSelectedIndex()).getLoaiNCID() : "",
                    chkCap.isSelected()? lstCap.get(cboCap.getSelectedIndex()).getCapID(): "",
                    chkHe.isSelected()? lstHe.get(cboHe.getSelectedIndex()).getHeID(): "",
                    maNV,
                    chkKhoaPhong.isSelected()? lstKP.get(cboKhoaPhong.getSelectedIndex()).getMaKP() : "");
            fillData.fillDataJTable(jTable1, header, rs);
            TableCellRenderer tcr;
            tcr = new ObjectCenterRenderer();
            jTable1.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(6).setCellRenderer(tcr);
            tcr = new DateRenderer();
            jTable1.getColumnModel().getColumn(5).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(7).setCellRenderer(tcr);
            if (jTable1.getRowCount() == 0){
                jTable1.setAutoResizeMode(1);
            } else {
                jTable1.setAutoResizeMode(0);
            }
            lblTongSo.setText("Tổng số: " + String.valueOf(jTable1.getRowCount()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtTacGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTacGiaFocusLost
        try {
            if (txtTacGia.getText().trim().length() == 0) {
                maNV = "";
                return;
            }
            ResultSet rs = actNV.getListNhanVien(txtTacGia.getText());
            rs.last();
            if (rs.getRow() > 0){
                if (rs.getRow() > 1){
                    JDialogSearchNhanVien frm = new JDialogSearchNhanVien((Frame) this.getParent(), true);
                    rs.first();
                    frm.loadData();
                    frm.setVisible(true);
                    txtTacGia.setText(frm.getHoTen());
                    maNV = frm.getMaNV();
                }
                else {
                    rs.first();
                    txtTacGia.setText(rs.getString("HoTen"));
                    maNV = rs.getString("MaNV");
                }
            }
            else {
                maNV = "";
                txtTacGia.setText("");
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_txtTacGiaFocusLost

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        ExcelExporter ex = new ExcelExporter();
        ex.fillData(jTable1);       
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        JDialogTenNCKH frm = new JDialogTenNCKH(null, true);
        frm.setVisible(true);
        btnRefreshActionPerformed(null);
    }//GEN-LAST:event_btnNewActionPerformed
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            JDialogTenNCKH frm = new JDialogTenNCKH(null, true);
            frm.setNckhID(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            frm.setVisible(true);
            btnRefreshActionPerformed(null);
        }
    }//GEN-LAST:event_btnEditActionPerformed
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            if (JOptionPane.showConfirmDialog(null, "Xoá đề tài, sáng kiến hiện tại phải không?", "Đề tài, sáng kiến", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                actTG.deleteTacGia(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                actTenNCKH.deleteTenNCKH(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                btnRefreshActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed



    private void mnuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewActionPerformed
        btnNewActionPerformed(null);
    }//GEN-LAST:event_mnuNewActionPerformed

    private void mnuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditActionPerformed
        btnEditActionPerformed(null);
    }//GEN-LAST:event_mnuEditActionPerformed

    private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
        btnDeleteActionPerformed(null);
    }//GEN-LAST:event_mnuDeleteActionPerformed

    private void mnuCongNhanNCKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCongNhanNCKHActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            JDialogCongNhanNCKH frm = new JDialogCongNhanNCKH(null, true);
            frm.setNckhID(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            frm.setTenNCKH(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            frm.setTacGia(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
            frm.setVisible(true);
            btnRefreshActionPerformed(null);           
        }
    }//GEN-LAST:event_mnuCongNhanNCKHActionPerformed

    private void mnuHuyCongNhanNCKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHuyCongNhanNCKHActionPerformed
        try {
            if (jTable1.getSelectedRow() >= 0){
                actTenNCKH.congNhanNCKH(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString(), 0, null, null);
                btnRefreshActionPerformed(null);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_mnuHuyCongNhanNCKHActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCongNhanNCKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongNhanNCKHActionPerformed
        mnuCongNhanNCKHActionPerformed(null);
    }//GEN-LAST:event_btnCongNhanNCKHActionPerformed

    private void mnuDuyetNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDuyetNopActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            actTenNCKH.updateNop(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString(), 1);
            btnRefreshActionPerformed(null);
        }
    }//GEN-LAST:event_mnuDuyetNopActionPerformed

    private void mnuHuyDuyetNopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHuyDuyetNopActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            actTenNCKH.updateNop(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString(), 0);
            btnRefreshActionPerformed(null);
        }

    }//GEN-LAST:event_mnuHuyDuyetNopActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCongNhanNCKH;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnInQD;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cboCap;
    private javax.swing.JComboBox cboHe;
    private javax.swing.JComboBox cboKhoaPhong;
    private javax.swing.JComboBox cboLoaiNC;
    private javax.swing.JCheckBox chkCap;
    private javax.swing.JCheckBox chkCongNhan;
    private javax.swing.JCheckBox chkHe;
    private javax.swing.JCheckBox chkKhoaPhong;
    private javax.swing.JCheckBox chkLoaiNC;
    private javax.swing.JCheckBox chkNop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTongSo;
    private javax.swing.JMenuItem mnuCongNhanNCKH;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuDuyetNop;
    private javax.swing.JMenuItem mnuEdit;
    private javax.swing.JMenuItem mnuHuyCongNhanNCKH;
    private javax.swing.JMenuItem mnuHuyDuyetNop;
    private javax.swing.JMenuItem mnuNew;
    private javax.swing.JSpinner txtNam;
    private javax.swing.JTextField txtTacGia;
    // End of variables declaration//GEN-END:variables

    private void loadData() throws Exception {
        loadLoaiNC();
        loadHe();
        loadCap();
        loadKhoaPhong();
    }
    private void loadLoaiNC() throws Exception{
        lstLoaiNC = actLoaiNC.getAllLoaiNC();
        cboLoaiNC.removeAllItems();
        for (LoaiNC dt:lstLoaiNC){
            cboLoaiNC.addItem(dt.getTenLoaiNC());
        }
    }
    private void loadHe() throws Exception{
        lstHe = actHe.getAllHe();
        cboHe.removeAllItems();
        for (He dt:lstHe){
            cboHe.addItem(dt.getTenHe());
        }
    }
    private void loadCap() throws Exception{
        lstCap = actCap.getAllCap();
        cboCap.removeAllItems();
        for (Cap dt:lstCap){
            cboCap.addItem(dt.getTenCap());
        }
    }
    private void loadKhoaPhong() throws Exception{
        lstKP = actKP.getAllKhoaPhong();
        cboKhoaPhong.removeAllItems();
        for (KhoaPhong kp:lstKP){
            cboKhoaPhong.addItem(kp.getTenKP());
        }
    }
}
