/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ChuyenVien;

import DataDB2.*;
import java.sql.Date;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author bvndc
 */

public class JInternalListChuyenDi extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalListChuyenDi
     */
    ActionChuyenDi actCD = new ActionChuyenDi();
    public JInternalListChuyenDi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuEdit = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuChuyen = new javax.swing.JMenuItem();
        mnuHuyChuyen = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTuNgay = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDenNgay = new javax.swing.JFormattedTextField();

        mnuEdit.setText("Sửa...");
        mnuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuEdit);

        mnuDelete.setText("Xoá...");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuDelete);
        jPopupMenu1.add(jSeparator1);

        mnuChuyen.setText("Chuyển");
        mnuChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChuyenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuChuyen);

        mnuHuyChuyen.setText("Huỷ chuyển");
        mnuHuyChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHuyChuyenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuHuyChuyen);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Danh sách chuyển viện");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EditTableHS.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GoToParentFolderHS.png"))); // NOI18N
        btnClose.setText("Đóng");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RefreshDocViewHS.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose)
                .addComponent(btnEdit)
                .addComponent(btnRefresh))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(javax.swing.UIManager.getDefaults().getColor("DesktopIcon.background"));
        jTable1.setShowVerticalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTable1CaretPositionChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Từ ngày:");

        txtTuNgay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel2.setText("Đến ngày:");

        txtDenNgay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDenNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadData(){
        String []header={"Mã chuyển", "Mã BN", "Họ tên BN", "Năm sinh", "Giới tính", "Địa chỉ", "Ngày chuyển", "Khoa", "Bác sĩ", "Đối tượng", "Số BHYT", "Trái tuyến", "Mã bênh", "Tên bệnh", "Bệnh viện", "Phương tiện", "Lý do", "Từ ngày", "Đến ngày", "Nội trú", "Đã chuyển"};
        try {
            FillData fillData = new FillData();
            ResultSet rs = actCD.getListChuyenDi(Date.valueOf(LocalDate.parse(txtTuNgay.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"))), Date.valueOf(LocalDate.parse(txtDenNgay.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
            fillData.fillDataJTable(jTable1, header, rs);           
            TableCellRenderer tcr;
            //tcr = new  CurrencyRenderer();
            //jTable1.getColumnModel().getColumn(19).setCellRenderer(tcr);
            tcr = new ObjectCenterRenderer();
            jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
            tcr = new DateRenderer();
            jTable1.getColumnModel().getColumn(6).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(17).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(18).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(11).setCellRenderer(tcr);
            //jTable1.getColumnModel().getColumn(11).setCellEditor(jTable1.getDefaultEditor(Boolean.class));  
            jTable1.setAutoResizeMode(jTable1.getRowCount() == 0? 1: 0);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            this.setMaximum(true);
            txtTuNgay.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            txtDenNgay.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            loadData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            JDialogChuyenDi frm = new JDialogChuyenDi(null, true);
            frm.setChuyenDiID(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
            frm.setNoiTru(Integer.valueOf(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 19))));
            frm.setVisible(true);
            loadData();            
        } else{
            JOptionPane.showMessageDialog(null, "Chưa chọn bệnh nhân!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void mnuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditActionPerformed
        // TODO add your handling code here:
        btnEditActionPerformed(evt);
    }//GEN-LAST:event_mnuEditActionPerformed

    private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
        if (jTable1.getSelectedRow() >= 0){
            String hoTen = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2));
            if (JOptionPane.showConfirmDialog(null, "Xoá bệnh nhân [" + hoTen + "] phải không?", "Chuyển viện", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                actCD.deleteChuyenDi(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
                loadData();
            }
        }
       
    }//GEN-LAST:event_mnuDeleteActionPerformed

    private void jTable1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1CaretPositionChanged
        String daChuyen = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 20));
        mnuChuyen.setEnabled(daChuyen == "0");
        mnuHuyChuyen.setEnabled(daChuyen == "1");    }//GEN-LAST:event_jTable1CaretPositionChanged

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        Integer daChuyen = Integer.valueOf(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 20)));
        mnuChuyen.setEnabled(daChuyen == 0);
        mnuHuyChuyen.setEnabled(daChuyen == 1);
    }//GEN-LAST:event_jTable1MousePressed

    private void mnuChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChuyenActionPerformed
        String chuyenVienID = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));        
        actCD.updateChuyenDi(chuyenVienID, 1);
        loadData();
        jTable1MousePressed(null);
    }//GEN-LAST:event_mnuChuyenActionPerformed

    private void mnuHuyChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHuyChuyenActionPerformed
        String chuyenVienID = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));        
        actCD.updateChuyenDi(chuyenVienID, 0);
        loadData();
        jTable1MousePressed(null);
    }//GEN-LAST:event_mnuHuyChuyenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mnuChuyen;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuEdit;
    private javax.swing.JMenuItem mnuHuyChuyen;
    private javax.swing.JFormattedTextField txtDenNgay;
    private javax.swing.JFormattedTextField txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
